apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-failure-home-timeline-service-mitigation
  namespace: social-network
spec:
  action: pod-failure
  mode: all
  selector:
    labelSelectors:
      app: home-timeline-service
