apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.global.persistentVolume.name }}
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.global.persistentVolume.storage }}
  accessModes:
    - {{ .Values.global.persistentVolume.accessModes }}
  hostPath:
    path: {{ .Values.global.persistentVolume.hostPath }}