name: user-mention-service

ports:
  - port: 9090
    targetPort: 9090
  - port: 9464
    targetPort: 9464

container:
  command: UserMentionService
  # image: beiz0109/social-network-test # deathstarbench/social-network-microservices
  image: fenglin02/social-network
  name: user-mention-service
  ports: 
  - containerPort: 9090
  - containerPort: 9464   # 添加9464端口映射

configMaps:
  - name: jaeger-config.yml
    mountPath: /config/jaeger-config.yml
    value: jaeger-config

  - name: service-config.json
    mountPath: /config/service-config.json
    value: service-config
