apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi  # You can adjust the storage size as needed
  storageClassName: standard  # Adjust the storage class if necessary (default is usually 'standard')
